version: "3.7"

networks:
  traefik:
    name: traefik

services:
  traefik:
    image: traefik:1.7-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme:/etc/traefik/acme
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend=traefik"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:${TRAEFIK_DOMAIN}"
