debug = false
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

  [entryPoints.traefik]
    address = ":8080"

[api]
  entryPoint = "traefik"
  dashboard = true

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false

[acme]
  email = "postmaster@guyteub.xyz"
  storage = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
  acmeLogging = true
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"
